### ISSUE TITLE
Link to solver broken

### ISSUE THREAD

**Issue by alexanderkjall** [p4-team/ctf#8]
I read through this writeup: https://github.com/p4-team/ctf/tree/master/2017-04-21-plaidctf/multicast

And the link to the solver returns a 404.

Otherwise great writeup.

**Comment by Pharisaeus** [comment]
Oh good point! I must have missed this file when committing changes to git. Anyway the whole solver is there already anyway since the main code is in the writeup and the one missing function is taken from linked resource (and the same result can be achieved with calling `.small_roots()` on the polynomial). I will fix this later. 
Thanks!

**Comment by Pharisaeus** [comment]
Fixed :)
